# Generated by Django 4.2.3 on 2023-08-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_content_type_alter_review_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, max_length=3000, verbose_name='comment'),
        ),
    ]
